/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_H_RPCGEN
#define _CLAVES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct respuesta {
	int result;
	char *value1;
	int value2;
	double value3;
};
typedef struct respuesta respuesta;

struct server_set_value_1_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct server_set_value_1_argument server_set_value_1_argument;

struct server_modify_value_1_argument {
	int key;
	char *arg2;
	int value2;
	double value3;
};
typedef struct server_modify_value_1_argument server_modify_value_1_argument;

struct server_copy_key_1_argument {
	int key1;
	int key2;
};
typedef struct server_copy_key_1_argument server_copy_key_1_argument;

#define CLAVES 99
#define OPERACIONESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define server_init 1
extern  enum clnt_stat server_init_1(int *, CLIENT *);
extern  bool_t server_init_1_svc(int *, struct svc_req *);
#define server_set_value 2
extern  enum clnt_stat server_set_value_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t server_set_value_1_svc(int , char *, int , double , int *, struct svc_req *);
#define server_get_value 3
extern  enum clnt_stat server_get_value_1(int , respuesta *, CLIENT *);
extern  bool_t server_get_value_1_svc(int , respuesta *, struct svc_req *);
#define server_delete_key 4
extern  enum clnt_stat server_delete_key_1(int , int *, CLIENT *);
extern  bool_t server_delete_key_1_svc(int , int *, struct svc_req *);
#define server_modify_value 5
extern  enum clnt_stat server_modify_value_1(int , char *, int , double , int *, CLIENT *);
extern  bool_t server_modify_value_1_svc(int , char *, int , double , int *, struct svc_req *);
#define server_exist 6
extern  enum clnt_stat server_exist_1(int , int *, CLIENT *);
extern  bool_t server_exist_1_svc(int , int *, struct svc_req *);
#define server_copy_key 7
extern  enum clnt_stat server_copy_key_1(int , int , int *, CLIENT *);
extern  bool_t server_copy_key_1_svc(int , int , int *, struct svc_req *);
extern int claves_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define server_init 1
extern  enum clnt_stat server_init_1();
extern  bool_t server_init_1_svc();
#define server_set_value 2
extern  enum clnt_stat server_set_value_1();
extern  bool_t server_set_value_1_svc();
#define server_get_value 3
extern  enum clnt_stat server_get_value_1();
extern  bool_t server_get_value_1_svc();
#define server_delete_key 4
extern  enum clnt_stat server_delete_key_1();
extern  bool_t server_delete_key_1_svc();
#define server_modify_value 5
extern  enum clnt_stat server_modify_value_1();
extern  bool_t server_modify_value_1_svc();
#define server_exist 6
extern  enum clnt_stat server_exist_1();
extern  bool_t server_exist_1_svc();
#define server_copy_key 7
extern  enum clnt_stat server_copy_key_1();
extern  bool_t server_copy_key_1_svc();
extern int claves_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_respuesta (XDR *, respuesta*);
extern  bool_t xdr_server_set_value_1_argument (XDR *, server_set_value_1_argument*);
extern  bool_t xdr_server_modify_value_1_argument (XDR *, server_modify_value_1_argument*);
extern  bool_t xdr_server_copy_key_1_argument (XDR *, server_copy_key_1_argument*);

#else /* K&R C */
extern bool_t xdr_respuesta ();
extern bool_t xdr_server_set_value_1_argument ();
extern bool_t xdr_server_modify_value_1_argument ();
extern bool_t xdr_server_copy_key_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_H_RPCGEN */
