/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"


void
claves_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int server_set_value_1_key;
	char *server_set_value_1_value1;
	int server_set_value_1_value2;
	double server_set_value_1_value3;
	enum clnt_stat retval_3;
	respuesta result_3;
	int server_get_value_1_key;
	enum clnt_stat retval_4;
	int result_4;
	int server_delete_key_1_key;
	enum clnt_stat retval_5;
	int result_5;
	int server_modify_value_1_key;
	char *server_modify_value_1_arg2;
	int server_modify_value_1_value2;
	double server_modify_value_1_value3;
	enum clnt_stat retval_6;
	int result_6;
	int server_exist_1_key;
	enum clnt_stat retval_7;
	int result_7;
	int server_copy_key_1_key1;
	int server_copy_key_1_key2;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES, OPERACIONESVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = server_init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = server_set_value_1(server_set_value_1_key, server_set_value_1_value1, server_set_value_1_value2, server_set_value_1_value3, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = server_get_value_1(server_get_value_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = server_delete_key_1(server_delete_key_1_key, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = server_modify_value_1(server_modify_value_1_key, server_modify_value_1_arg2, server_modify_value_1_value2, server_modify_value_1_value3, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = server_exist_1(server_exist_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = server_copy_key_1(server_copy_key_1_key1, server_copy_key_1_key2, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	claves_1 (host);
exit (0);
}
