/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "claves.h"


void
claves_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	int set_value_1_key;
	char *set_value_1_value1;
	int set_value_1_value2;
	double set_value_1_value3;
	enum clnt_stat retval_3;
	respuesta result_3;
	int get_value_1_key;
	enum clnt_stat retval_4;
	int result_4;
	int modify_value_1_key;
	char *modify_value_1_value1;
	int modify_value_1_value2;
	double modify_value_1_value3;
	enum clnt_stat retval_5;
	int result_5;
	int delete_value_1_key;
	enum clnt_stat retval_6;
	int result_6;
	enum clnt_stat retval_7;
	int result_7;
	int copy_key_1_key1;
	int copy_key_1_key2;

#ifndef	DEBUG
	clnt = clnt_create (host, CLAVES, CLAVESVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = init_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = set_value_1(set_value_1_key, set_value_1_value1, set_value_1_value2, set_value_1_value3, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = get_value_1(get_value_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = modify_value_1(modify_value_1_key, modify_value_1_value1, modify_value_1_value2, modify_value_1_value3, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_value_1(delete_value_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = exist_1(&result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = copy_key_1(copy_key_1_key1, copy_key_1_key2, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	claves_1 (host);
exit (0);
}
